# docker-compose.yml
version: '3.8'

services:
  jekyll:
    image: jekyll/builder:latest
    volumes:
      - .:/srv/jekyll
      - ./_site:/srv/jekyll/_site
    command: jekyll build --future
    environment:
      - JEKYLL_ENV=production